### ISSUE TITLE
Mysterious make error

### ISSUE THREAD

**Issue by xoviat** [conda-forge/flang-feedstock#4]
When attempting to rebuild, I ran into the following error:

https://circleci.com/gh/conda-forge/flang-feedstock/15?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

```
 69%] Linking Fortran shared library ../../lib/libflang.so
[ 69%] Built target flang_shared
make: *** [all] Error 2
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/opt/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 342, in main
    execute(sys.argv[1:])
  File "/opt/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 333, in execute
    noverify=args.no_verify)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/api.py", line 97, in build
    need_source_download=need_source_download, config=config)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 1524, in build_tree
    config=config)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 1147, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/utils.py", line 628, in check_call_env
    return _func_defaulting_env_to_os_environ(subprocess.check_call, *popenargs, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/utils.py", line 624, in _func_defaulting_env_to_os_environ
    return func(_args, **kwargs)
  File "/opt/conda/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bin/bash', '-x', '-e', '/feedstock_root/build_artefacts/flang_1513363100961/work/flang-b2391791218ab17e6cecaba47fc49bf1bd593a62/conda_build.sh']' returned non-zero exit status 2.
+ exit 1
```

This doesn't really provide any useful information and it compiles fine locally.

**Comment by isuruf** [comment]
You have to scroll up a bit to see the actual error
```
F90-F-0004-Corrupt or Old Module file ../../include/omp_lib_kinds.mod (/feedstock_root/build_artefacts/flang_1513363100961/work/flang-b2391791218ab17e6cecaba47fc49bf1bd593a62/runtime/flang/omp_lib.F95: 121)
F90/x86-64 Linux Flang - 1.5 2017-05-01: compilation aborted
make[2]: *** [runtime/flang/CMakeFiles/flang_static.dir/omp_lib.F95.o] Error 1
make[1]: *** [runtime/flang/CMakeFiles/flang_static.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```
The error is a parallel make issue
